import React, { FunctionComponent, useEffect, useRef, useState } from "react";

import Head from "next/head";
import Image from "next/image";

import DrinkSearchResults from "../components/DrinkSearchResults";
import SearchInput from "../components/SearchInput";
import { THIRSTY_DRINK_FINDER } from "../constants/messaging";
import { BASE_API_URL } from "../constants/urls";
import styles from "../styles/Home.module.css";

const Home: FunctionComponent = () => {
  const [searchResults, setSearchResults] = useState([]);
  const searchHandler = async (input: string) => {
    const res = await fetch(
      `${BASE_API_URL}/api/json/v1/1/search.php?s=${input}`
    );
    const { drinks } = await res.json();
    setSearchResults(drinks);
  };
  const searchInputRef = useRef<HTMLInputElement>(null);
  useEffect(() => {
    searchInputRef?.current?.focus?.();
  }, []);
  return (
    <div className={styles.pageContainer}>
      <Head>
        <title>{THIRSTY_DRINK_FINDER}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/martini.ico" />
      </Head>
      <div className={styles.contentContainer}>
        <Image src="/thirsty.svg" alt="Thirsty Logo" width={500} height={250} />
        <SearchInput changeHandler={(e) => searchHandler(e.target.value)} />
        <DrinkSearchResults
          currentInput={searchInputRef?.current?.value}
          drinks={searchResults}
        />
      </div>
    </div>
  );
};
export default Home;
