import React, { FunctionComponent, useEffect, useRef, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import DrinkSearchResult from "../components/DrinkSearchResult";
import { Drink } from "../types";

const Home: FunctionComponent = () => {
  const [searchResults, setSearchResults] = useState([]);
  const searchHandler = async (input: string) => {
    const res = await fetch(
      `https://www.thecocktaildb.com/api/json/v1/1/search.php?s=${input}`
    );

    const { drinks } = await res.json();

    setSearchResults(drinks);
  };
  const searchInputRef = useRef<HTMLInputElement>(null);
  useEffect(() => {
    searchInputRef?.current?.focus?.();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Thirsty Drink Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.inputContainer}>
        <Image
          src="/../public/thirsty.png"
          alt=""
          width="300px"
          height="400px"
        />
        <input
          className={styles.input}
          onChange={(e) => searchHandler(e.target.value)}
          ref={searchInputRef}
        />
        {searchResults?.map((drink: Drink) => {
          return <DrinkSearchResult drink={drink} key={drink?.strDrink} />;
        })}
      </div>
    </div>
  );
};
export default Home;
